# Generated by Django 2.0.6 on 2019-03-01 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('school', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('workDate', models.DateField(default=datetime.date(2019, 3, 1))),
                ('entryDate', models.DateTimeField(default=datetime.datetime(2019, 3, 1, 15, 53, 18, 574838))),
            ],
        ),
    ]
